### ISSUE TITLE
Compilation warning on CLang

### ISSUE THREAD

**Issue by msv68** [fungos/fips-imgui#5]
CLang compiler does not support the option -Wno-unused-but-set-variable. It reports warning about it. It is because the file CMakeLists.txt contains the following:
<pre>
if (FIPS_CLANG)
    set_target_properties(imgui PROPERTIES COMPILE_FLAGS "-Wno-unused-but-set-variable -Wno-type-limits -Wno-missing-field-initializers")
</pre>

Please remove this option from CLang compile flags.

**Comment by fungos** [comment]
Hi, we changed the official repository to a fips organization, you can get the most up-to-date and correct fips-imgui here: https://github.com/fips-libs/fips-imgui
This fix are already there, see: https://github.com/fips-libs/fips-imgui/blob/master/CMakeLists.txt#L105

**Comment by msv68** [comment]
OK, thanks. 
Then in order to avoid such confusions in the future I propose to change the link in FIPS project to the correct fipsified imgui site. I have found the current site through that link.
